fps: 25
sampling_rate: 16000

input_size: 512 # input resolution
input_nc: 3

dim_m: 20
dim_a: 512
dim_w: 512
dim_h: 1024
dim_e: 8
dim_p: 6
dim_g: 2
style_dim: 512

num_train_timestep: 1000
nfe: 10

sec: 2
num_context: 10
num_frames_per_block: 10
only_last_features: False

audio_dropout_prob: 0.1
ref_dropout_prob: 0.1

a_cfg_scale: 2.0
r_cfg_scale: 1.0

fix_noise_seed: False

# Transformer Hyper Parameters
attention_window: 2
num_heads: 8
mlp_ratio: 4.0
transformer_depth: 8
block_causal: True

mixed_precision: True

tmp_dir: 'tmp'
pretrained_dir: 'pretrained_dir'
wav2vec_model_path: pretrained_dir/wav2vec2-base-960h
